query AllJobs {
    jobs {
        id
        title
        slug
        company {
            name
            slug
        }
        tags {
            id
            name
        }
        postedAt
    }
}